<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	  <LangVersion>latest</LangVersion>
    <Version>1.0.1</Version>
	  <Deterministic>true</Deterministic>
	  <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
	
  <PropertyGroup>
	  <WarningsAsErrors>$(WarningsAsErrors);NU1605;AsyncFixer03</WarningsAsErrors>
  </PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="AsyncFixer" Version="2.1.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Ben.Demystifier" Version="0.4.1" />
		<PackageReference Include="log4net" Version="3.3.0" />
		<PackageReference Include="prometheus-net" Version="8.2.1" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DeepCore\DeepCore.Geometry\DeepCore.Geometry.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepCore.Template.MoonSharp\DeepCore.Template.MoonSharp.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepCore.Template.NewtonJson\DeepCore.Template.NewtonJson.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepCore.Voxel\DeepCore.Voxel.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepCore\DeepCore.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepCrystal\DeepCrystal.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepOpenAI\DeepOpenAI.csproj" />
    <ProjectReference Include="..\..\DeepCore\Gate.Data\Gate.Data.csproj" />
    <ProjectReference Include="..\..\DeepCore\Gate.Server\Gate.Server.csproj" />
    <ProjectReference Include="..\..\DeepCore\MMO.Server\MMO.Server.csproj" />
    <ProjectReference Include="..\_Temp_.Battle\_Temp_.Battle.csproj" />
    <ProjectReference Include="..\_Temp_.Codec\_Temp_.Codec.csproj" />
  </ItemGroup>
</Project>