<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>1.0.1</Version>
	  <Deterministic>true</Deterministic>
	  <Configurations>Debug;Release;Source</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="generated_orm\**" />
    <EmbeddedResource Remove="generated_orm\**" />
    <None Remove="generated_orm\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="msg_code.json" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\DeepCore\DeepCore.GUI\DeepCore.GUI.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepCore\DeepCore.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepMetaGame.Data\DeepMetaGame.Data.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepMetaGame.Host\DeepMetaGame.Host.csproj" />
    <ProjectReference Include="..\..\DeepCore\DeepMetaGame.Slave\DeepMetaGame.Slave.csproj" />
    <ProjectReference Include="..\..\DeepCore\Gate.Data\Gate.Data.csproj" />
    <ProjectReference Include="..\_Temp_.Battle\_Temp_.Battle.csproj" />
  </ItemGroup>
	
</Project>