<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.0.1</Version>
		<Deterministic>true</Deterministic>
		<LangVersion>latest</LangVersion>
		<Configurations>Debug;Release;Source</Configurations>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="generated_cartridge\**" />
	  <Compile Remove="Host\BattleComp\**" />
	  <Compile Remove="Host\Components\**" />
	  <EmbeddedResource Remove="generated_cartridge\**" />
	  <EmbeddedResource Remove="Host\BattleComp\**" />
	  <EmbeddedResource Remove="Host\Components\**" />
	  <None Remove="generated_cartridge\**" />
	  <None Remove="Host\BattleComp\**" />
	  <None Remove="Host\Components\**" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\DeepCore\DeepCore\DeepCore.csproj" />
	  <ProjectReference Include="..\..\DeepCore\DeepMetaGame.Data\DeepMetaGame.Data.csproj" />
	  <ProjectReference Include="..\..\DeepCore\DeepMetaGame.Display\DeepMetaGame.Display.csproj" />
	  <ProjectReference Include="..\..\DeepCore\DeepMetaGame.Host\DeepMetaGame.Host.csproj" />
	  <ProjectReference Include="..\..\DeepCore\DeepMetaGame.Slave\DeepMetaGame.Slave.csproj" />
	</ItemGroup>
	
</Project>