<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Version>1.0.1</Version>
		<Deterministic>true</Deterministic>
		<Configurations>Debug;Release;Source</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="LevelDB.DataCenter\**" />
		<Compile Remove="LevelDB\**" />
		<EmbeddedResource Remove="LevelDB.DataCenter\**" />
		<EmbeddedResource Remove="LevelDB\**" />
		<None Remove="LevelDB.DataCenter\**" />
		<None Remove="LevelDB\**" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\DeepCore\DeepCore\DeepCore.csproj" />
		<ProjectReference Include="..\..\DeepCore\DeepMetaGame.Data\DeepMetaGame.Data.csproj" />
		<ProjectReference Include="..\..\DeepCore\DeepMetaGame.Display\DeepMetaGame.Display.csproj" />
		<ProjectReference Include="..\..\DeepCore\DeepMetaGame.Host\DeepMetaGame.Host.csproj" />
		<ProjectReference Include="..\..\DeepCore\DeepMetaGame.Slave\DeepMetaGame.Slave.csproj" />
		<ProjectReference Include="..\..\DeepCore\Gate.Client\Gate.Client.csproj" />
		<ProjectReference Include="..\..\DeepCore\Gate.Data\Gate.Data.csproj" />
		<ProjectReference Include="..\..\DeepCore\MMO.Client\MMO.Client.csproj" />
		<ProjectReference Include="..\_Temp_.Battle\_Temp_.Battle.csproj" />
		<ProjectReference Include="..\_Temp_.Protocol\_Temp_.Protocol.csproj" />
	</ItemGroup>
</Project>